### PR TITLE
Attempts to fix issues with windows

### PR DESCRIPTION
**Pull request by aarondandy**
I have no idea what I am doing but this Works on My Machine so it's totally legit, I'm sure 😉. Also, I'm not sure `.raw` is needed and after reading the docs there is no guarantee that you will even have that property. I did notice that on my machine that I can't load the `der` at all, so make sure I didn't break that!

no idea

### CODE REVIEW

**Comment by jcrowgey** [comment]
HI!  Were you able to run the tests?  I probably need to set up travis for this project. :)

**Comment by aarondandy** [comment]
I'll try to figure that out next. Many conventions and idioms to learn still.

**Comment by aarondandy** [comment]
Pytest passes for both my commit and master on my WSL environment. Pytest fails on my Windows environment for both commits.

**Comment by jcrowgey** [comment]
I ran the tests against your branch and all seems fine.  I also tried as many funny corner cases I could thing of to try to make `isatty` give a false negative and as far as I can tell, everything still works as I expect on GNU/Linux.

I'm happy to merge this.

Feel free to open an issue regarding DER encoded certs.

**Pull request merged**
